//! Baby JubJub curve helpers for Global View Key encryption.
//!
//! Manual port of circomlib's twisted Edwards arithmetic, matching
//! `circuits/src/test/utils/babyjub.rs`. We avoid `ark-ed-on-bn254` because
//! it uses a normalized curve form incompatible with the in-circuit semantics.

#![allow(clippy::arithmetic_side_effects)]

use crate::{
    types::{BabyJubJubPoint, Field},
    zk::serialization::{field_to_scalar, scalar_to_field},
};
use ark_bn254::Fr as Scalar;
use ark_ff::{BigInteger, Field as _, One, PrimeField, Zero};
use core::str::FromStr;

/// The circomlib Baby JubJub generator `BASE8` (prime-order subgroup).
const BASE8_X: &str =
    "5299619240641551281634865583518297030282874472190772894086521144482721001553";
const BASE8_Y: &str =
    "16950150798460657717958625567821834550301663161624707787222815936182638968203";

/// An affine Baby JubJub point in circomlib coordinates. The identity is
/// `(0, 1)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Point {
    pub x: Scalar,
    pub y: Scalar,
}

/// The group identity `(0, 1)`.
pub fn identity() -> Point {
    Point {
        x: Scalar::zero(),
        y: Scalar::one(),
    }
}

/// The circomlib `BASE8` generator.
pub fn base8() -> Point {
    Point {
        x: Scalar::from_str(BASE8_X).expect("Invalid BASE8 x coordinate"),
        y: Scalar::from_str(BASE8_Y).expect("Invalid BASE8 y coordinate"),
    }
}

/// Build a point from field-element coordinates.
///
/// The point is not validated, mirroring the circuit's treatment of an
/// untrusted public `D`.
pub fn point_from_coords(x: Scalar, y: Scalar) -> Point {
    Point { x, y }
}

/// Return a point's coordinates.
pub fn point_to_coords(p: Point) -> (Scalar, Scalar) {
    (p.x, p.y)
}

/// Complete twisted Edwards addition, matching circomlib's `BabyAdd`.
///
/// Returns `None` only when a denominator is not invertible.
pub fn add(p: Point, q: Point) -> Option<Point> {
    let a = Scalar::from(168700u64);
    let d = Scalar::from(168696u64);
    let beta = p.x * q.y;
    let gamma = p.y * q.x;
    let delta = (p.y - a * p.x) * (q.x + q.y);
    let tau = beta * gamma;

    let x_den = (Scalar::one() + d * tau).inverse()?;
    let y_den = (Scalar::one() - d * tau).inverse()?;

    Some(Point {
        x: (beta + gamma) * x_den,
        y: (delta + a * beta - gamma) * y_den,
    })
}

/// Point doubling, matching circomlib's `BabyDbl`.
pub fn double(p: Point) -> Option<Point> {
    add(p, p)
}

/// Multiply `point` by the integer value of `scalar` via double-and-add.
///
/// Not constant-time (branches on scalar bits).
pub fn scalar_mul(point: Point, scalar: Scalar) -> Option<Point> {
    let mut acc = identity();
    let mut base = point;
    for bit in scalar.into_bigint().to_bits_le() {
        if bit {
            acc = add(acc, base)?;
        }
        base = double(base)?;
    }
    Some(acc)
}

/// Clear the cofactor: return `8 * point` (three doublings).
pub fn mul8(point: Point) -> Option<Point> {
    double(double(double(point)?)?)
}

impl Point {
    /// Whether this point satisfies the Baby JubJub curve equation.
    pub fn is_on_curve(self) -> bool {
        let a = Scalar::from(168700u64);
        let d = Scalar::from(168696u64);
        let x2 = self.x * self.x;
        let y2 = self.y * self.y;
        a * x2 + y2 == Scalar::one() + d * x2 * y2
    }
}

impl BabyJubJubPoint {
    /// Returns `scalar * BASE8`.
    pub fn from_priv_scalar(scalar: &Field) -> Option<Self> {
        Some(Self::from_point(scalar_mul(
            base8(),
            field_to_scalar(scalar),
        )?))
    }

    pub(crate) fn to_coords(&self) -> (Scalar, Scalar) {
        (field_to_scalar(&self.x), field_to_scalar(&self.y))
    }

    pub(crate) fn from_coords(x: Scalar, y: Scalar) -> Self {
        Self {
            x: scalar_to_field(&x),
            y: scalar_to_field(&y),
        }
    }

    fn from_point(p: Point) -> Self {
        let (x, y) = point_to_coords(p);
        Self::from_coords(x, y)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The prime order of the Baby JubJub subgroup generated by `BASE8`.
    const SUBGROUP_ORDER: &str =
        "2736030358979909402780800718157159386076813972158567259200215660948447373041";

    #[test]
    fn base8_is_on_curve() {
        assert!(base8().is_on_curve());
    }

    #[test]
    fn base8_has_prime_order() {
        let l = Scalar::from_str(SUBGROUP_ORDER).expect("valid subgroup order");
        assert_eq!(scalar_mul(base8(), l), Some(identity()));
    }

    #[test]
    fn mul8_matches_three_doublings() {
        let g = base8();
        assert_eq!(mul8(g), scalar_mul(g, Scalar::from(8u64)));
    }

    #[test]
    fn scalar_mul_is_homomorphic() {
        let g = base8();
        let a = Scalar::from(123456u64);
        let b = Scalar::from(654321u64);
        assert_eq!(
            scalar_mul(g, a + b),
            add(
                scalar_mul(g, a).expect("valid scalar mul"),
                scalar_mul(g, b).expect("valid scalar mul")
            )
        );
    }
}
