use std::{
    env, fs,
    path::{Path, PathBuf},
};
use stellar_private_payments::{
    circuits::{ArtifactKind, verify_artifact_bytes},
    types::CircuitStem,
};

fn repo_root_from_manifest_dir(manifest_dir: &Path) -> PathBuf {
    manifest_dir
        .ancestors()
        .nth(2)
        .expect("sdk/web/build.rs: expected crate at sdk/web")
        .to_path_buf()
}

fn read_file(path: &Path) -> Vec<u8> {
    fs::read(path)
        .unwrap_or_else(|e| panic!("sdk/web/build.rs: failed to read {}: {e}", path.display()))
}

fn assert_lockfile_match(stem: &str, kind: ArtifactKind, bytes: &[u8]) {
    verify_artifact_bytes(stem, kind, bytes).unwrap_or_else(|e| {
        panic!(
            "sdk/web/build.rs: {} does not match embedded circuits.json: {e}",
            stellar_private_payments::artifact_file_name(stem, kind)
        )
    });
}

fn artifact_paths(repo_root: &Path, stem: &str) -> (PathBuf, PathBuf, PathBuf) {
    let keys_dir = repo_root.join("deployments/testnet/circuit_keys");
    let circuits_out = repo_root.join("target/circuits-artifacts");
    (
        keys_dir.join(format!("{stem}_proving_key.bin")),
        keys_dir.join(format!("{stem}.graph.bin")),
        circuits_out.join(format!("{stem}.r1cs")),
    )
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = repo_root_from_manifest_dir(&manifest_dir);
    let circuits_out = repo_root.join("target/circuits-artifacts");

    if !circuits_out.is_dir() {
        panic!(
            "sdk/web/build.rs: missing circuit artifacts directory: {}. Run `make circuits` first.",
            circuits_out.display(),
        );
    }

    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:rerun-if-changed={}",
        repo_root.join("sdk/native/circuits.json").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        repo_root
            .join("sdk/native/src/types/circuit_stem.rs")
            .display()
    );

    for var in [
        "E2E_STATIC_ORIGIN",
        "E2E_RPC_URL",
        "E2E_BOOTNODE_URL",
        "E2E_POOL_CONTRACT",
        "E2E_ACCOUNT_A_ADDRESS",
        "E2E_ACCOUNT_B_ADDRESS",
    ] {
        println!("cargo:rerun-if-env-changed={var}");
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let mut bundled_proving_key_arms = String::new();

    for stem in CircuitStem::all_transact_stems() {
        let stem = stem.to_string();
        let (proving_key_path, graph_path, r1cs_path) = artifact_paths(&repo_root, &stem);

        println!("cargo:rerun-if-changed={}", proving_key_path.display());
        println!("cargo:rerun-if-changed={}", graph_path.display());
        println!("cargo:rerun-if-changed={}", r1cs_path.display());

        let proving_key_bytes = read_file(&proving_key_path);
        let graph_bytes = read_file(&graph_path);
        let r1cs_bytes = read_file(&r1cs_path);

        assert_lockfile_match(&stem, ArtifactKind::ProvingKey, &proving_key_bytes);
        assert_lockfile_match(&stem, ArtifactKind::Graph, &graph_bytes);
        assert_lockfile_match(&stem, ArtifactKind::R1cs, &r1cs_bytes);

        fs::write(
            out_dir.join(format!("{stem}_proving_key.bin")),
            &proving_key_bytes,
        )
        .unwrap_or_else(|e| {
            panic!(
                "sdk/web/build.rs: failed to write {}: {e}",
                out_dir.join(format!("{stem}_proving_key.bin")).display()
            )
        });

        bundled_proving_key_arms.push_str(&format!(
            "
        \"{stem}\" => Some(include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}_proving_key.bin\"))),",
        ));
    }

    for n_notes in 1..=4 {
        let stem = format!("selectiveDisclosure_{n_notes}");
        let (proving_key_path, graph_path, r1cs_path) = artifact_paths(&repo_root, &stem);

        println!("cargo:rerun-if-changed={}", proving_key_path.display());
        println!("cargo:rerun-if-changed={}", graph_path.display());
        println!("cargo:rerun-if-changed={}", r1cs_path.display());

        assert_lockfile_match(
            &stem,
            ArtifactKind::ProvingKey,
            &read_file(&proving_key_path),
        );
        assert_lockfile_match(&stem, ArtifactKind::Graph, &read_file(&graph_path));
        assert_lockfile_match(&stem, ArtifactKind::R1cs, &read_file(&r1cs_path));
    }

    let out = format!(
        "// @generated by sdk/web/build.rs

pub fn bundled_policy_proving_key(stem: &str) -> Option<&'static [u8]> {{
    match stem {{{bundled_proving_key_arms}
        _ => None,
    }}
}}
"
    );

    let out_path = out_dir.join("bundled_proving_keys.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| {
        panic!(
            "sdk/web/build.rs: failed to write {}: {e}",
            out_path.display()
        )
    });
}
