use sha2::{Digest, Sha256};
use std::{
    env, fs,
    path::{Path, PathBuf},
};
use stellar_private_payments::types::PolicyFlags;

fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest[..]);
    out
}

fn fmt_u8_array(bytes: &[u8]) -> String {
    let mut out = String::from("[");
    for (idx, b) in bytes.iter().enumerate() {
        if idx != 0 {
            out.push_str(", ");
        }
        out.push_str(&b.to_string());
    }
    out.push(']');
    out
}

fn repo_root_from_manifest_dir(manifest_dir: &Path) -> PathBuf {
    manifest_dir
        .ancestors()
        .nth(2)
        .expect("sdk/web/build.rs: expected crate at sdk/web")
        .to_path_buf()
}

fn read_file(path: &Path) -> Vec<u8> {
    fs::read(path)
        .unwrap_or_else(|e| panic!("sdk/web/build.rs: failed to read {}: {e}", path.display()))
}

fn copy_artifact(src: &Path, out_dir: &Path, name: &str) -> Vec<u8> {
    let bytes = read_file(src);
    fs::write(out_dir.join(name), &bytes).unwrap_or_else(|e| {
        panic!(
            "sdk/web/build.rs: failed to write {}: {e}",
            out_dir.join(name).display()
        )
    });
    bytes
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = repo_root_from_manifest_dir(&manifest_dir);

    let circuits_out = repo_root.join("target/circuits-artifacts");

    if !circuits_out.is_dir() {
        panic!(
            "sdk/web/build.rs: missing circuit artifacts directory: {}. Run `make circuits` first.",
            circuits_out.display(),
        );
    }

    println!("cargo:rerun-if-changed=build.rs");

    // Non-secret e2e config only.
    for var in [
        "E2E_STATIC_ORIGIN",
        "E2E_RPC_URL",
        "E2E_BOOTNODE_URL",
        "E2E_POOL_CONTRACT",
        "E2E_ACCOUNT_A_ADDRESS",
        "E2E_ACCOUNT_B_ADDRESS",
    ] {
        println!("cargo:rerun-if-env-changed={var}");
    }
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir
            .join("../../sdk/native/src/types/policy_tx.rs")
            .display()
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let mut out = String::from("// @generated by sdk/web/build.rs\n\n");
    let mut policy_lookup_arms = String::new();
    let mut policy_stem_literals = String::new();
    let mut bundled_proving_key_arms = String::new();

    for stem in PolicyFlags::all_stems() {
        let keys_dir = repo_root.join("deployments/testnet/circuit_keys");
        let proving_key_path = keys_dir.join(format!("{stem}_proving_key.bin"));
        let graph_path = keys_dir.join(format!("{stem}.graph.bin"));
        let r1cs_path = circuits_out.join(format!("{stem}.r1cs"));

        println!("cargo:rerun-if-changed={}", proving_key_path.display());
        println!("cargo:rerun-if-changed={}", graph_path.display());
        println!("cargo:rerun-if-changed={}", r1cs_path.display());

        let proving_key_bytes = read_file(&proving_key_path);
        copy_artifact(
            &proving_key_path,
            &out_dir,
            &format!("{stem}_proving_key.bin"),
        );
        let graph_bytes = copy_artifact(&graph_path, &out_dir, &format!("{stem}.graph.bin"));
        let r1cs_bytes = copy_artifact(&r1cs_path, &out_dir, &format!("{stem}.r1cs"));

        let proving_key_hash = sha256(&proving_key_bytes);
        let graph_hash = sha256(&graph_bytes);
        let r1cs_hash = sha256(&r1cs_bytes);
        let const_prefix = stem.to_ascii_uppercase();

        out.push_str(&format!(
            "
pub const EXPECTED_{const_prefix}_PROVING_KEY_SHA256: [u8; 32] = {proving_key_hash};
pub const EXPECTED_{const_prefix}_GRAPH_SHA256: [u8; 32] = {graph_hash};
pub const EXPECTED_{const_prefix}_R1CS_SHA256: [u8; 32] = {r1cs_hash};

pub const EXPECTED_{const_prefix}_PROVING_KEY_LEN: usize = {proving_key_len};
pub const EXPECTED_{const_prefix}_GRAPH_LEN: usize = {graph_len};
pub const EXPECTED_{const_prefix}_R1CS_LEN: usize = {r1cs_len};
",
            proving_key_hash = fmt_u8_array(&proving_key_hash),
            graph_hash = fmt_u8_array(&graph_hash),
            r1cs_hash = fmt_u8_array(&r1cs_hash),
            proving_key_len = proving_key_bytes.len(),
            graph_len = graph_bytes.len(),
            r1cs_len = r1cs_bytes.len(),
        ));
        policy_lookup_arms.push_str(&format!(
            "
        \"{stem}\" => Some(PolicyTransactArtifactHashes {{
            proving_key_len: EXPECTED_{const_prefix}_PROVING_KEY_LEN,
            proving_key_sha256: EXPECTED_{const_prefix}_PROVING_KEY_SHA256,
            graph_len: EXPECTED_{const_prefix}_GRAPH_LEN,
            graph_sha256: EXPECTED_{const_prefix}_GRAPH_SHA256,
            r1cs_len: EXPECTED_{const_prefix}_R1CS_LEN,
            r1cs_sha256: EXPECTED_{const_prefix}_R1CS_SHA256,
        }}),",
        ));
        policy_stem_literals.push_str(&format!("\n    \"{stem}\","));
        bundled_proving_key_arms.push_str(&format!(
            "
        \"{stem}\" => Some(include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}_proving_key.bin\"))),",
        ));
    }

    out.push_str(&format!(
        "
pub const POLICY_TRANSACT_CIRCUIT_STEMS: &[&str] = &[{policy_stem_literals}
];

pub fn bundled_policy_proving_key(stem: &str) -> Option<&'static [u8]> {{
    match stem {{{bundled_proving_key_arms}
        _ => None,
    }}
}}
",
    ));

    out.push_str(
        "
#[derive(Clone, Copy, Debug)]
pub struct PolicyTransactArtifactHashes {
    pub proving_key_len: usize,
    pub proving_key_sha256: [u8; 32],
    pub graph_len: usize,
    pub graph_sha256: [u8; 32],
    pub r1cs_len: usize,
    pub r1cs_sha256: [u8; 32],
}

pub fn policy_transact_artifact_hashes(stem: &str) -> Option<PolicyTransactArtifactHashes> {
    match stem {
",
    );
    out.push_str(&policy_lookup_arms);
    out.push_str(
        "
        _ => None,
    }
}
",
    );

    for n_notes in 1..=4 {
        let stem = format!("selectiveDisclosure_{n_notes}");
        let keys_dir = repo_root.join("deployments/testnet/circuit_keys");
        let pk_path = keys_dir.join(format!("{stem}_proving_key.bin"));
        let disc_graph_path = keys_dir.join(format!("{stem}.graph.bin"));
        let disc_r1cs_path = circuits_out.join(format!("{stem}.r1cs"));

        println!("cargo:rerun-if-changed={}", pk_path.display());
        println!("cargo:rerun-if-changed={}", disc_graph_path.display());
        println!("cargo:rerun-if-changed={}", disc_r1cs_path.display());

        let pk_bytes = read_file(&pk_path);
        let disc_graph_bytes =
            copy_artifact(&disc_graph_path, &out_dir, &format!("{stem}.graph.bin"));
        let disc_r1cs_bytes = copy_artifact(&disc_r1cs_path, &out_dir, &format!("{stem}.r1cs"));

        let pk_hash = sha256(&pk_bytes);
        let disc_graph_hash = sha256(&disc_graph_bytes);
        let disc_r1cs_hash = sha256(&disc_r1cs_bytes);

        let suffix = stem
            .strip_prefix("selectiveDisclosure_")
            .expect("stem must start with 'selectiveDisclosure_'");
        let const_prefix = format!("SELECTIVE_DISCLOSURE_{suffix}");

        out.push_str(&format!(
            "
pub const EXPECTED_{const_prefix}_PROVING_KEY_SHA256: [u8; 32] = {pk_hash};
pub const EXPECTED_{const_prefix}_GRAPH_SHA256: [u8; 32] = {disc_graph_hash};
pub const EXPECTED_{const_prefix}_R1CS_SHA256: [u8; 32] = {disc_r1cs_hash};

pub const EXPECTED_{const_prefix}_PROVING_KEY_LEN: usize = {pk_len};
pub const EXPECTED_{const_prefix}_GRAPH_LEN: usize = {disc_graph_len};
pub const EXPECTED_{const_prefix}_R1CS_LEN: usize = {disc_r1cs_len};
",
            pk_hash = fmt_u8_array(&pk_hash),
            disc_graph_hash = fmt_u8_array(&disc_graph_hash),
            disc_r1cs_hash = fmt_u8_array(&disc_r1cs_hash),
            pk_len = pk_bytes.len(),
            disc_graph_len = disc_graph_bytes.len(),
            disc_r1cs_len = disc_r1cs_bytes.len(),
        ));
    }

    let out_path = out_dir.join("artifact_hashes.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| {
        panic!(
            "sdk/web/build.rs: failed to write {}: {e}",
            out_path.display()
        )
    });
}
