use sha2::{Digest, Sha256};
use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest[..]);
    out
}

fn fmt_u8_array(bytes: &[u8]) -> String {
    let mut out = String::from("[");
    for (idx, b) in bytes.iter().enumerate() {
        if idx != 0 {
            out.push_str(", ");
        }
        out.push_str(&b.to_string());
    }
    out.push(']');
    out
}

fn repo_root_from_manifest_dir(manifest_dir: &Path) -> PathBuf {
    manifest_dir
        .ancestors()
        .nth(4)
        .expect("web/build.rs: expected web crate to be at app/crates/platforms/web")
        .to_path_buf()
}

fn read_file(path: &Path) -> Vec<u8> {
    fs::read(path)
        .unwrap_or_else(|e| panic!("web/build.rs: failed to read {}: {e}", path.display()))
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = repo_root_from_manifest_dir(&manifest_dir);

    let proving_key_path =
        repo_root.join("deployments/testnet/circuit_keys/policy_tx_2_2_proving_key.bin");

    let profile = env::var("PROFILE").expect("PROFILE env var is set by Cargo");
    let circuits_out = repo_root.join("target/circuits-artifacts").join(&profile);

    if !circuits_out.is_dir() {
        let suggestion = if profile == "release" {
            "cargo build -p circuits --release"
        } else {
            "cargo build -p circuits"
        };
        panic!(
            "web/build.rs: missing circuit artifacts directory for PROFILE={profile}: {}. Run `{suggestion}` first.",
            circuits_out.display(),
        );
    }

    let wasm_path = circuits_out.join("policy_tx_2_2.wasm");
    let r1cs_path = circuits_out.join("policy_tx_2_2.r1cs");

    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-changed={}", proving_key_path.display());
    println!("cargo:rerun-if-changed={}", wasm_path.display());
    println!("cargo:rerun-if-changed={}", r1cs_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let proving_key_bytes = read_file(&proving_key_path);
    let wasm_bytes = read_file(&wasm_path);
    let r1cs_bytes = read_file(&r1cs_path);

    let proving_key_hash = sha256(&proving_key_bytes);
    let wasm_hash = sha256(&wasm_bytes);
    let r1cs_hash = sha256(&r1cs_bytes);

    let mut out = format!(
        "\
// @generated by app/crates/platforms/web/build.rs
// Do not edit manually.

pub const EXPECTED_POLICY_TX_2_2_PROVING_KEY_SHA256: [u8; 32] = {proving_key_hash};
pub const EXPECTED_POLICY_TX_2_2_WASM_SHA256: [u8; 32] = {wasm_hash};
pub const EXPECTED_POLICY_TX_2_2_R1CS_SHA256: [u8; 32] = {r1cs_hash};

pub const EXPECTED_POLICY_TX_2_2_PROVING_KEY_LEN: usize = {proving_key_len};
pub const EXPECTED_POLICY_TX_2_2_WASM_LEN: usize = {wasm_len};
pub const EXPECTED_POLICY_TX_2_2_R1CS_LEN: usize = {r1cs_len};
",
        proving_key_hash = fmt_u8_array(&proving_key_hash),
        wasm_hash = fmt_u8_array(&wasm_hash),
        r1cs_hash = fmt_u8_array(&r1cs_hash),
        proving_key_len = proving_key_bytes.len(),
        wasm_len = wasm_bytes.len(),
        r1cs_len = r1cs_bytes.len(),
    );

    let mut disclosure_files: Vec<(String, PathBuf, PathBuf, PathBuf)> = Vec::new();
    for n_notes in 1..=4 {
        let stem = format!("selectiveDisclosure_{n_notes}");
        let pk_path = repo_root
            .join("deployments/testnet/circuit_keys")
            .join(format!("{stem}_proving_key.bin"));
        let wasm_path = circuits_out.join(format!("{stem}.wasm"));
        let r1cs_path = circuits_out.join(format!("{stem}.r1cs"));

        println!("cargo:rerun-if-changed={}", pk_path.display());
        println!("cargo:rerun-if-changed={}", wasm_path.display());
        println!("cargo:rerun-if-changed={}", r1cs_path.display());

        disclosure_files.push((stem, pk_path, wasm_path, r1cs_path));
    }

    for (stem, pk_path, wasm_path, r1cs_path) in &disclosure_files {
        let pk_bytes = read_file(pk_path);
        let wasm_bytes = read_file(wasm_path);
        let r1cs_bytes = read_file(r1cs_path);

        let pk_hash = sha256(&pk_bytes);
        let wasm_hash = sha256(&wasm_bytes);
        let r1cs_hash = sha256(&r1cs_bytes);

        // The stem is e.g. "selectiveDisclosure_1"; uppercase with underscore
        // separation gives "SELECTIVE_DISCLOSURE_1".
        let suffix = stem
            .strip_prefix("selectiveDisclosure_")
            .expect("stem must start with 'selectiveDisclosure_'");
        let const_prefix = format!("SELECTIVE_DISCLOSURE_{suffix}");

        out.push_str(&format!(
            "
pub const EXPECTED_{const_prefix}_PROVING_KEY_SHA256: [u8; 32] = {pk_hash};
pub const EXPECTED_{const_prefix}_WASM_SHA256: [u8; 32] = {wasm_hash};
pub const EXPECTED_{const_prefix}_R1CS_SHA256: [u8; 32] = {r1cs_hash};

pub const EXPECTED_{const_prefix}_PROVING_KEY_LEN: usize = {pk_len};
pub const EXPECTED_{const_prefix}_WASM_LEN: usize = {wasm_len};
pub const EXPECTED_{const_prefix}_R1CS_LEN: usize = {r1cs_len};
",
            pk_hash = fmt_u8_array(&pk_hash),
            wasm_hash = fmt_u8_array(&wasm_hash),
            r1cs_hash = fmt_u8_array(&r1cs_hash),
            pk_len = pk_bytes.len(),
            wasm_len = wasm_bytes.len(),
            r1cs_len = r1cs_bytes.len(),
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("artifact_hashes.rs");

    fs::write(&out_path, out)
        .unwrap_or_else(|e| panic!("web/build.rs: failed to write {}: {e}", out_path.display()));
}
