use sha2::{Digest, Sha256};
use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&digest[..]);
    out
}

fn fmt_u8_array(bytes: &[u8]) -> String {
    let mut out = String::from("[");
    for (idx, b) in bytes.iter().enumerate() {
        if idx != 0 {
            out.push_str(", ");
        }
        out.push_str(&b.to_string());
    }
    out.push(']');
    out
}

fn repo_root_from_manifest_dir(manifest_dir: &Path) -> PathBuf {
    manifest_dir
        .ancestors()
        .nth(4)
        .expect("web/build.rs: expected web crate to be at app/crates/platforms/web")
        .to_path_buf()
}

fn read_file(path: &Path) -> Vec<u8> {
    fs::read(path)
        .unwrap_or_else(|e| panic!("web/build.rs: failed to read {}: {e}", path.display()))
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = repo_root_from_manifest_dir(&manifest_dir);

    let proving_key_path =
        repo_root.join("deployments/testnet/circuit_keys/policy_tx_2_2_proving_key.bin");
    let disclosure_proving_key_path =
        repo_root.join("deployments/testnet/circuit_keys/selectiveDisclosure_1_proving_key.bin");
    // Committed circom-witness-rs graphs for witness generation
    let policy_graph_path =
        repo_root.join("deployments/testnet/circuit_keys/policy_tx_2_2.graph.bin");
    let disclosure_graph_path =
        repo_root.join("deployments/testnet/circuit_keys/selectiveDisclosure_1.graph.bin");

    let profile = env::var("PROFILE").expect("PROFILE env var is set by Cargo");
    let circuits_out = repo_root.join("target/circuits-artifacts").join(&profile);

    let r1cs_path = circuits_out.join("policy_tx_2_2.r1cs");
    let disclosure_r1cs_path = circuits_out.join("selectiveDisclosure_1.r1cs");

    // These r1cs files are published by the `circuits` build, not by cargo's
    // dependency graph, so a bare `cargo build` can race ahead of them. The
    // `make build`/`make serve` targets sequence `circuits-build` first.
    if !circuits_out.is_dir() || !r1cs_path.exists() || !disclosure_r1cs_path.exists() {
        panic!(
            "web/build.rs: circuit artifacts for PROFILE={profile} are missing under {}. \
             Build the circuits first (`cargo build -p circuits --release`), or build the app via `make build` / \
             `make serve`, which sequence this automatically.",
            circuits_out.display(),
        );
    }

    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-changed={}", proving_key_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        disclosure_proving_key_path.display()
    );
    println!("cargo:rerun-if-changed={}", policy_graph_path.display());
    println!("cargo:rerun-if-changed={}", disclosure_graph_path.display());
    println!("cargo:rerun-if-changed={}", r1cs_path.display());
    println!("cargo:rerun-if-changed={}", disclosure_r1cs_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let proving_key_bytes = read_file(&proving_key_path);
    let disclosure_proving_key_bytes = read_file(&disclosure_proving_key_path);
    let r1cs_bytes = read_file(&r1cs_path);
    let disclosure_r1cs_bytes = read_file(&disclosure_r1cs_path);
    let policy_graph_bytes = read_file(&policy_graph_path);
    let disclosure_graph_bytes = read_file(&disclosure_graph_path);

    let proving_key_hash = sha256(&proving_key_bytes);
    let disclosure_proving_key_hash = sha256(&disclosure_proving_key_bytes);
    let r1cs_hash = sha256(&r1cs_bytes);
    let disclosure_r1cs_hash = sha256(&disclosure_r1cs_bytes);
    let policy_graph_hash = sha256(&policy_graph_bytes);
    let disclosure_graph_hash = sha256(&disclosure_graph_bytes);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("artifact_hashes.rs");

    let contents = format!(
        "\
// @generated by app/crates/platforms/web/build.rs
// Do not edit manually.

pub const EXPECTED_POLICY_TX_2_2_PROVING_KEY_SHA256: [u8; 32] = {proving_key_hash};
pub const EXPECTED_POLICY_TX_2_2_R1CS_SHA256: [u8; 32] = {r1cs_hash};

pub const EXPECTED_POLICY_TX_2_2_PROVING_KEY_LEN: usize = {proving_key_len};
pub const EXPECTED_POLICY_TX_2_2_R1CS_LEN: usize = {r1cs_len};

pub const EXPECTED_POLICY_TX_2_2_GRAPH_SHA256: [u8; 32] = {policy_graph_hash};
pub const EXPECTED_POLICY_TX_2_2_GRAPH_LEN: usize = {policy_graph_len};

pub const EXPECTED_SELECTIVE_DISCLOSURE_1_PROVING_KEY_SHA256: [u8; 32] = {disclosure_proving_key_hash};
pub const EXPECTED_SELECTIVE_DISCLOSURE_1_R1CS_SHA256: [u8; 32] = {disclosure_r1cs_hash};

pub const EXPECTED_SELECTIVE_DISCLOSURE_1_PROVING_KEY_LEN: usize = {disclosure_proving_key_len};
pub const EXPECTED_SELECTIVE_DISCLOSURE_1_R1CS_LEN: usize = {disclosure_r1cs_len};

pub const EXPECTED_SELECTIVE_DISCLOSURE_1_GRAPH_SHA256: [u8; 32] = {disclosure_graph_hash};
pub const EXPECTED_SELECTIVE_DISCLOSURE_1_GRAPH_LEN: usize = {disclosure_graph_len};
",
        proving_key_hash = fmt_u8_array(&proving_key_hash),
        r1cs_hash = fmt_u8_array(&r1cs_hash),
        proving_key_len = proving_key_bytes.len(),
        r1cs_len = r1cs_bytes.len(),
        disclosure_proving_key_hash = fmt_u8_array(&disclosure_proving_key_hash),
        disclosure_r1cs_hash = fmt_u8_array(&disclosure_r1cs_hash),
        disclosure_proving_key_len = disclosure_proving_key_bytes.len(),
        disclosure_r1cs_len = disclosure_r1cs_bytes.len(),
        policy_graph_hash = fmt_u8_array(&policy_graph_hash),
        policy_graph_len = policy_graph_bytes.len(),
        disclosure_graph_hash = fmt_u8_array(&disclosure_graph_hash),
        disclosure_graph_len = disclosure_graph_bytes.len(),
    );

    fs::write(&out_path, contents)
        .unwrap_or_else(|e| panic!("web/build.rs: failed to write {}: {e}", out_path.display()));
}
