#!/usr/bin/env bash
# Tar a working Freighter profile into a snapshot for reuse across e2e runs.
#
# CI provisioning decision:
#   Default:  commit this snapshot as a repo release asset. It is stable
#             across runs (the vault is app-level password-encrypted; the
#             unlock password lives in CI secrets as E2E_FREIGHTER_PASSWORD,
#             matching deployments/testnet/.e2e-accounts.env locally), so CI
#             just downloads + restores it instead of re-provisioning.
#   Fallback: if the snapshot goes stale (extension update breaks the vault
#             format, etc.), fall back to scripted onboarding per run via
#             scripts/setup-freighter-profile.mjs, which reprovisions a
#             fresh profile from scratch.
#
# Usage: snapshot-profile.sh [--profile-dir DIR] [--out FILE]

set -euo pipefail

die() { echo "snapshot-profile.sh: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing '$1'"; }
step() { echo "==> $*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

PROFILE_DIR="$PKG_ROOT/.chrome-profile"
OUT_FILE="$PKG_ROOT/profile-snapshot.tar.gz"

usage() {
  cat >&2 <<'USAGE'
Usage: snapshot-profile.sh [OPTIONS]

Tars a working Freighter Chrome profile (extension loaded, account imported,
sidebar mode enabled — the profile built by scripts/setup-freighter-profile.mjs)
into a snapshot archive, excluding cache directories that only bloat the tar
and are safely regenerated by Chrome on next launch.

Options:
  --profile-dir DIR   Profile directory to snapshot (default: .chrome-profile)
  --out FILE           Output archive path (default: profile-snapshot.tar.gz)
  -h, --help           Show this help

Examples:
  e2e-freighter/scripts/snapshot-profile.sh
  e2e-freighter/scripts/snapshot-profile.sh --profile-dir .chrome-profile --out profile-snapshot.tar.gz
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --profile-dir) [ $# -ge 2 ] || die "--profile-dir needs a value"; PROFILE_DIR="$2"; shift 2 ;;
    --out) [ $# -ge 2 ] || die "--out needs a value"; OUT_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) usage; die "unknown argument '$1'" ;;
  esac
done

need tar

[ -d "$PROFILE_DIR" ] || die "profile dir '$PROFILE_DIR' not found; run scripts/setup-freighter-profile.mjs first"

# Cache dirs Chrome regenerates on its own; excluding them keeps the
# snapshot small and avoids baking in machine-specific junk. Do NOT exclude
# by a bare "*.log" pattern: LevelDB's write-ahead logs (e.g.
# "Local Extension Settings/<id>/000003.log") use that same extension and
# hold not-yet-compacted writes — excluding them silently drops recent
# extension storage (this cost a full profile rebuild to find). Chrome's
# own top-level debug log is named literally "chrome_debug.log", so exclude
# that by exact name instead.
EXCLUDES=(
  --exclude="GPUCache"
  --exclude="Code Cache"
  --exclude="ShaderCache"
  --exclude="GrShaderCache"
  --exclude="component_crx_cache"
  --exclude="extensions_crx_cache"
  --exclude="chrome_debug.log"
  --exclude="SingletonLock"
  --exclude="SingletonSocket"
  --exclude="SingletonCookie"
)

step "snapshotting '$PROFILE_DIR' -> '$OUT_FILE'"
tar -czf "$OUT_FILE" "${EXCLUDES[@]}" -C "$(dirname "$PROFILE_DIR")" "$(basename "$PROFILE_DIR")"
step "wrote $OUT_FILE ($(du -h "$OUT_FILE" | cut -f1))"
